/*
 * The Q&A EIST Twitter API
 * Allows the SlackBot to Interact with the TweetWall
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ActiveSlidePathPPTKEY
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-26T20:33:23.745+02:00")
public class ActiveSlidePathPPTKEY {
  @SerializedName("pptslide")
  private String pptslide = null;

  @SerializedName("keyslide")
  private String keyslide = null;

  @SerializedName("devslide")
  private String devslide = null;

  public ActiveSlidePathPPTKEY pptslide(String pptslide) {
    this.pptslide = pptslide;
    return this;
  }

   /**
   * Get pptslide
   * @return pptslide
  **/
  @ApiModelProperty(value = "")
  public String getPptslide() {
    return pptslide;
  }

  public void setPptslide(String pptslide) {
    this.pptslide = pptslide;
  }

  public ActiveSlidePathPPTKEY keyslide(String keyslide) {
    this.keyslide = keyslide;
    return this;
  }

   /**
   * Get keyslide
   * @return keyslide
  **/
  @ApiModelProperty(value = "")
  public String getKeyslide() {
    return keyslide;
  }

  public void setKeyslide(String keyslide) {
    this.keyslide = keyslide;
  }

  public ActiveSlidePathPPTKEY devslide(String devslide) {
    this.devslide = devslide;
    return this;
  }

   /**
   * Get devslide
   * @return devslide
  **/
  @ApiModelProperty(value = "")
  public String getDevslide() {
    return devslide;
  }

  public void setDevslide(String devslide) {
    this.devslide = devslide;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActiveSlidePathPPTKEY activeSlidePathPPTKEY = (ActiveSlidePathPPTKEY) o;
    return Objects.equals(this.pptslide, activeSlidePathPPTKEY.pptslide) &&
        Objects.equals(this.keyslide, activeSlidePathPPTKEY.keyslide) &&
        Objects.equals(this.devslide, activeSlidePathPPTKEY.devslide);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pptslide, keyslide, devslide);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActiveSlidePathPPTKEY {\n");
    
    sb.append("    pptslide: ").append(toIndentedString(pptslide)).append("\n");
    sb.append("    keyslide: ").append(toIndentedString(keyslide)).append("\n");
    sb.append("    devslide: ").append(toIndentedString(devslide)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

