/*
 * The Q&A EIST Twitter API
 * Allows the SlackBot to Interact with the TweetWall
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Reply;
import java.util.ArrayList;
import java.util.List;

/**
 * Question
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-27T12:59:10.118+02:00")
public class Question {
  @SerializedName("id")
  private String id = null;

  @SerializedName("content")
  private String content = null;

  @SerializedName("author")
  private String author = null;

  @SerializedName("date")
  private String date = null;

  @SerializedName("upvotes")
  private Integer upvotes = null;

  @SerializedName("slideSet")
  private Integer slideSet = null;

  @SerializedName("slide")
  private Integer slide = null;

  @SerializedName("slideURL")
  private String slideURL = null;

  @SerializedName("replies")
  private List<Reply> replies = new ArrayList<Reply>();

  @SerializedName("bestanswer")
  private Reply bestanswer = null;

  public Question id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Question content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public Question author(String author) {
    this.author = author;
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAuthor() {
    return author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public Question date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public Question upvotes(Integer upvotes) {
    this.upvotes = upvotes;
    return this;
  }

   /**
   * Get upvotes
   * @return upvotes
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getUpvotes() {
    return upvotes;
  }

  public void setUpvotes(Integer upvotes) {
    this.upvotes = upvotes;
  }

  public Question slideSet(Integer slideSet) {
    this.slideSet = slideSet;
    return this;
  }

   /**
   * Get slideSet
   * @return slideSet
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSlideSet() {
    return slideSet;
  }

  public void setSlideSet(Integer slideSet) {
    this.slideSet = slideSet;
  }

  public Question slide(Integer slide) {
    this.slide = slide;
    return this;
  }

   /**
   * Get slide
   * @return slide
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSlide() {
    return slide;
  }

  public void setSlide(Integer slide) {
    this.slide = slide;
  }

  public Question slideURL(String slideURL) {
    this.slideURL = slideURL;
    return this;
  }

   /**
   * Get slideURL
   * @return slideURL
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSlideURL() {
    return slideURL;
  }

  public void setSlideURL(String slideURL) {
    this.slideURL = slideURL;
  }

  public Question replies(List<Reply> replies) {
    this.replies = replies;
    return this;
  }

  public Question addRepliesItem(Reply repliesItem) {
    this.replies.add(repliesItem);
    return this;
  }

   /**
   * Get replies
   * @return replies
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Reply> getReplies() {
    return replies;
  }

  public void setReplies(List<Reply> replies) {
    this.replies = replies;
  }

  public Question bestanswer(Reply bestanswer) {
    this.bestanswer = bestanswer;
    return this;
  }

   /**
   * Get bestanswer
   * @return bestanswer
  **/
  @ApiModelProperty(example = "null", value = "")
  public Reply getBestanswer() {
    return bestanswer;
  }

  public void setBestanswer(Reply bestanswer) {
    this.bestanswer = bestanswer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Question question = (Question) o;
    return Objects.equals(this.id, question.id) &&
        Objects.equals(this.content, question.content) &&
        Objects.equals(this.author, question.author) &&
        Objects.equals(this.date, question.date) &&
        Objects.equals(this.upvotes, question.upvotes) &&
        Objects.equals(this.slideSet, question.slideSet) &&
        Objects.equals(this.slide, question.slide) &&
        Objects.equals(this.slideURL, question.slideURL) &&
        Objects.equals(this.replies, question.replies) &&
        Objects.equals(this.bestanswer, question.bestanswer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, content, author, date, upvotes, slideSet, slide, slideURL, replies, bestanswer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Question {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    upvotes: ").append(toIndentedString(upvotes)).append("\n");
    sb.append("    slideSet: ").append(toIndentedString(slideSet)).append("\n");
    sb.append("    slide: ").append(toIndentedString(slide)).append("\n");
    sb.append("    slideURL: ").append(toIndentedString(slideURL)).append("\n");
    sb.append("    replies: ").append(toIndentedString(replies)).append("\n");
    sb.append("    bestanswer: ").append(toIndentedString(bestanswer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

