/*
 * The Q&A EIST Twitter API
 * Allows the SlackBot to Interact with the TweetWall
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * SingleShotQuestion
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-25T16:44:55.040+02:00")
public class SingleShotQuestion {
  @SerializedName("id")
  private String id = null;

  @SerializedName("date")
  private String date = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("answerKeyText")
  private Map<String, String> answerKeyText = new HashMap<String, String>();

  @SerializedName("firstCorrect")
  private Integer firstCorrect = null;

  @SerializedName("fastestAnswers")
  private List<String> fastestAnswers = new ArrayList<String>();

  @SerializedName("votes")
  private Map<String, String> votes = new HashMap<String, String>();

  @SerializedName("content")
  private String content = null;

  @SerializedName("correctAnswerNumber")
  private Integer correctAnswerNumber = null;

  @SerializedName("slideSet")
  private Integer slideSet = null;

  @SerializedName("slide")
  private Integer slide = null;

  @SerializedName("slideURL")
  private String slideURL = null;

  public SingleShotQuestion id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SingleShotQuestion date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public SingleShotQuestion name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SingleShotQuestion answerKeyText(Map<String, String> answerKeyText) {
    this.answerKeyText = answerKeyText;
    return this;
  }

  public SingleShotQuestion putAnswerKeyTextItem(String key, String answerKeyTextItem) {
    this.answerKeyText.put(key, answerKeyTextItem);
    return this;
  }

   /**
   * Get answerKeyText
   * @return answerKeyText
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, String> getAnswerKeyText() {
    return answerKeyText;
  }

  public void setAnswerKeyText(Map<String, String> answerKeyText) {
    this.answerKeyText = answerKeyText;
  }

  public SingleShotQuestion firstCorrect(Integer firstCorrect) {
    this.firstCorrect = firstCorrect;
    return this;
  }

   /**
   * Get firstCorrect
   * @return firstCorrect
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getFirstCorrect() {
    return firstCorrect;
  }

  public void setFirstCorrect(Integer firstCorrect) {
    this.firstCorrect = firstCorrect;
  }

  public SingleShotQuestion fastestAnswers(List<String> fastestAnswers) {
    this.fastestAnswers = fastestAnswers;
    return this;
  }

  public SingleShotQuestion addFastestAnswersItem(String fastestAnswersItem) {
    this.fastestAnswers.add(fastestAnswersItem);
    return this;
  }

   /**
   * Get fastestAnswers
   * @return fastestAnswers
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getFastestAnswers() {
    return fastestAnswers;
  }

  public void setFastestAnswers(List<String> fastestAnswers) {
    this.fastestAnswers = fastestAnswers;
  }

  public SingleShotQuestion votes(Map<String, String> votes) {
    this.votes = votes;
    return this;
  }

  public SingleShotQuestion putVotesItem(String key, String votesItem) {
    this.votes.put(key, votesItem);
    return this;
  }

   /**
   * Get votes
   * @return votes
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, String> getVotes() {
    return votes;
  }

  public void setVotes(Map<String, String> votes) {
    this.votes = votes;
  }

  public SingleShotQuestion content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public SingleShotQuestion correctAnswerNumber(Integer correctAnswerNumber) {
    this.correctAnswerNumber = correctAnswerNumber;
    return this;
  }

   /**
   * Get correctAnswerNumber
   * @return correctAnswerNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getCorrectAnswerNumber() {
    return correctAnswerNumber;
  }

  public void setCorrectAnswerNumber(Integer correctAnswerNumber) {
    this.correctAnswerNumber = correctAnswerNumber;
  }

  public SingleShotQuestion slideSet(Integer slideSet) {
    this.slideSet = slideSet;
    return this;
  }

   /**
   * Get slideSet
   * @return slideSet
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSlideSet() {
    return slideSet;
  }

  public void setSlideSet(Integer slideSet) {
    this.slideSet = slideSet;
  }

  public SingleShotQuestion slide(Integer slide) {
    this.slide = slide;
    return this;
  }

   /**
   * Get slide
   * @return slide
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSlide() {
    return slide;
  }

  public void setSlide(Integer slide) {
    this.slide = slide;
  }

  public SingleShotQuestion slideURL(String slideURL) {
    this.slideURL = slideURL;
    return this;
  }

   /**
   * Get slideURL
   * @return slideURL
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSlideURL() {
    return slideURL;
  }

  public void setSlideURL(String slideURL) {
    this.slideURL = slideURL;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SingleShotQuestion singleShotQuestion = (SingleShotQuestion) o;
    return Objects.equals(this.id, singleShotQuestion.id) &&
        Objects.equals(this.date, singleShotQuestion.date) &&
        Objects.equals(this.name, singleShotQuestion.name) &&
        Objects.equals(this.answerKeyText, singleShotQuestion.answerKeyText) &&
        Objects.equals(this.firstCorrect, singleShotQuestion.firstCorrect) &&
        Objects.equals(this.fastestAnswers, singleShotQuestion.fastestAnswers) &&
        Objects.equals(this.votes, singleShotQuestion.votes) &&
        Objects.equals(this.content, singleShotQuestion.content) &&
        Objects.equals(this.correctAnswerNumber, singleShotQuestion.correctAnswerNumber) &&
        Objects.equals(this.slideSet, singleShotQuestion.slideSet) &&
        Objects.equals(this.slide, singleShotQuestion.slide) &&
        Objects.equals(this.slideURL, singleShotQuestion.slideURL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, date, name, answerKeyText, firstCorrect, fastestAnswers, votes, content, correctAnswerNumber, slideSet, slide, slideURL);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SingleShotQuestion {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    answerKeyText: ").append(toIndentedString(answerKeyText)).append("\n");
    sb.append("    firstCorrect: ").append(toIndentedString(firstCorrect)).append("\n");
    sb.append("    fastestAnswers: ").append(toIndentedString(fastestAnswers)).append("\n");
    sb.append("    votes: ").append(toIndentedString(votes)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    correctAnswerNumber: ").append(toIndentedString(correctAnswerNumber)).append("\n");
    sb.append("    slideSet: ").append(toIndentedString(slideSet)).append("\n");
    sb.append("    slide: ").append(toIndentedString(slide)).append("\n");
    sb.append("    slideURL: ").append(toIndentedString(slideURL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

