/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jan' at '3/27/17 11:50 AM' with Gradle 2.6
 *
 * @author jan, @date 3/27/17 11:50 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
